language: node_js
sudo: false
node_js:
- 'lts/*'
install:
- yarn
cache:
  yarn: true
  directories:
  - node_modules

jobs:
  include:
  - stage: deploy
    name: on npm
    if: tag
    script: 'true' # skips tests
    deploy:
    - provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      skip_cleanup: true
      on:
        tags: true